auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 192.168.0.167
    netmask 255.255.255.0
    gateway 192.168.0.1

auto eth1
iface eth1 inet static
    address 192.168.1.64
    netmask 255.255.255.0
    gateway 192.168.1.1

auto eth2
iface eth2 inet static
    address 192.168.2.199
    netmask 255.255.255.0
    gateway 192.168.2.1

auto eth3
iface eth3 inet static
    address 192.168.3.240
    netmask 255.255.255.0
    gateway 192.168.3.1

auto eth4
iface eth4 inet static
    address 192.168.4.91
    netmask 255.255.255.0
    gateway 192.168.4.1

auto eth5
iface eth5 inet dhcp

auto eth6
iface eth6 inet dhcp

auto eth7
iface eth7 inet static
    address 192.168.7.226
    netmask 255.255.255.0
    gateway 192.168.7.1

