auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 192.168.0.70
    netmask 255.255.255.0
    gateway 192.168.0.1

auto eth1
iface eth1 inet static
    address 192.168.1.51
    netmask 255.255.255.0
    gateway 192.168.1.1

auto eth2
iface eth2 inet static
    address 192.168.2.112
    netmask 255.255.255.0
    gateway 192.168.2.1

auto eth3
iface eth3 inet dhcp

