auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
    address 192.168.1.149
    netmask 255.255.255.0
    gateway 192.168.1.1

auto eth2
iface eth2 inet dhcp

auto eth3
iface eth3 inet static
    address 192.168.3.34
    netmask 255.255.255.0
    gateway 192.168.3.1

auto eth4
iface eth4 inet static
    address 192.168.4.10
    netmask 255.255.255.0
    gateway 192.168.4.1

