auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 192.168.0.165
    netmask 255.255.255.0
    gateway 192.168.0.1

auto eth1
iface eth1 inet dhcp

auto eth2
iface eth2 inet dhcp

auto eth3
iface eth3 inet dhcp

auto eth4
iface eth4 inet dhcp

auto eth5
iface eth5 inet static
    address 192.168.5.45
    netmask 255.255.255.0
    gateway 192.168.5.1

auto eth6
iface eth6 inet dhcp

auto eth7
iface eth7 inet static
    address 192.168.7.17
    netmask 255.255.255.0
    gateway 192.168.7.1

auto eth8
iface eth8 inet dhcp

