auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
    address 192.168.1.68
    netmask 255.255.255.0
    gateway 192.168.1.1

auto eth2
iface eth2 inet dhcp

auto eth3
iface eth3 inet dhcp

auto eth4
iface eth4 inet static
    address 192.168.4.107
    netmask 255.255.255.0
    gateway 192.168.4.1

auto eth5
iface eth5 inet dhcp

auto eth6
iface eth6 inet static
    address 192.168.6.72
    netmask 255.255.255.0
    gateway 192.168.6.1

auto eth7
iface eth7 inet dhcp

auto eth8
iface eth8 inet static
    address 192.168.8.199
    netmask 255.255.255.0
    gateway 192.168.8.1

