auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 192.168.0.2
    netmask 255.255.255.0
    gateway 192.168.0.1

auto eth1
iface eth1 inet static
    address 192.168.1.232
    netmask 255.255.255.0
    gateway 192.168.1.1

auto eth2
iface eth2 inet static
    address 192.168.2.144
    netmask 255.255.255.0
    gateway 192.168.2.1

auto eth3
iface eth3 inet dhcp

auto eth4
iface eth4 inet dhcp

auto eth5
iface eth5 inet static
    address 192.168.5.161
    netmask 255.255.255.0
    gateway 192.168.5.1

